# Generated by Django 5.1.7 on 2025-05-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('defective', 'Defective')], default='active', max_length=20)),
                ('battery_level', models.IntegerField(default=100)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('firmware_version', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('glucose_level', models.FloatField(help_text='Blood glucose level in mg/dL')),
                ('heart_rate', models.IntegerField(help_text='Heart rate in BPM')),
                ('temperature', models.FloatField(help_text='Body temperature in °C')),
                ('blood_oxygen', models.IntegerField(blank=True, help_text='Blood oxygen level in %', null=True)),
                ('steps', models.IntegerField(default=0)),
                ('calories', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Device Data',
                'verbose_name_plural': 'Device Data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
